global:
  image:
    tag: "v2.12.0"

configs:
  params:
    # Enable insecure mode for local development
    server.insecure: true
    # Disable TLS for local development
    server.grpc.web: true
    
  cm:
    # Allow applications in any namespace
    application.instanceLabelKey: argocd.argoproj.io/instance
    # Enable exec for troubleshooting
    exec.enabled: "true"
    # Configure URL for local access
    url: "https://argocd.local"
    
  # Configure repositories
  repositories: |
    - type: git
      url: https://github.com/argoproj/argocd-example-apps.git
    - name: argo-helm
      type: helm
      url: https://argoproj.github.io/argo-helm

server:
  # Enable insecure mode for local development
  extraArgs:
    - --insecure
  
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
  
  ingress:
    enabled: false
  
  # Resource limits for local development
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

controller:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

repoServer:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

redis:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

applicationSet:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

notifications:
  enabled: false

# Enable RBAC
rbac:
  create: true
  
# Create service account
serviceAccount:
  create: true
  name: argocd-server
