alertmanager:
    config:
        global:
            resolve_timeout: 5m
        route:
            group_by: [ 'job' ]
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: 'null'
            routes:
                -   match:
                        alertname: Watchdog
                    receiver: 'null'
        receivers:
            -   name: 'null'

    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 50m
            memory: 64Mi

    persistentVolume:
        enabled: true
        size: 2Gi

securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    runAsGroup: 1000
    fsGroup: 1000