replicas: 1

clusterName: "elasticsearch"
nodeGroup: "master"

# Minimum cluster size for production is 3 masters, 2 data, 2 client
# Updated format for roles (list instead of map)
roles:
    - master
    - ingest
    - data

# The service account to be used by the deployment
serviceAccount:
    create: true

# The security context for pods
podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000

# The security context for containers
securityContext:
    capabilities:
        drop:
            - ALL
    runAsNonRoot: true
    runAsUser: 1000

# Number of memory in MB for initial heap size, half of the container memory limit
esJavaOpts: "-Xmx512m -Xms512m"

resources:
    requests:
        cpu: "250m"
        memory: "1Gi"
    limits:
        cpu: "500m"
        memory: "1Gi"

volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
        requests:
            storage: 10Gi

antiAffinity: "soft"

# This is the setting for single node development setup
maxUnavailable: 1

# Node labels for pod assignment
nodeSelector: { }

# Tolerations for pod assignment
tolerations: [ ]

# Allow access from all domains
httpPort: 9200
transportPort: 9300

# Elasticsearch configuration
esConfig:
    elasticsearch.yml: |
        xpack.security.enabled: false
        discovery.type: single-node
        network.host: 0.0.0.0
        http.port: 9200
        transport.port: 9300
        cluster.initial_master_nodes: "elasticsearch-master-0"

# Image settings
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"

# Environment variables
extraEnvs:
    - name: ELASTIC_PASSWORD
      value: "changeme"
    - name: discovery.type
      value: single-node