global:
    storageClass: ""

image:
    registry: docker.io
    repository: bitnami/kafka
    tag: latest
    pullPolicy: IfNotPresent

kraft:
    enabled: true
    clusterId: "kafka-cluster-local"

zookeeper:
    enabled: false

controller:
    replicaCount: 1  # 3+ in prod
    persistence:
        enabled: true
        size: 8Gi

broker:
    replicaCount: 1  # 3+ in prod
    persistence:
        enabled: true
        size: 8Gi

listeners:
    client:
        name: CLIENT
        port: 9092
        protocol: PLAINTEXT
    controller:
        name: CONTROLLER
        port: 9093
        protocol: PLAINTEXT
    interbroker:
        name: INTERNAL
        port: 9094
        protocol: PLAINTEXT

resources:
    limits:
        cpu: 500m
        memory: 1Gi
    requests:
        cpu: 250m
        memory: 512Mi

# Kafka config
extraConfig: |
    auto.create.topics.enable=true
    delete.topic.enable=true
    num.partitions=3
    default.replication.factor=1
    log.retention.hours=24
    log.retention.bytes=1073741824